### ISSUE TITLE
Adding License to OMNA registrations

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#10]
The mockup indicates the addition of a new field to collect the type of license.
 * https://www.screencast.com/t/TBFt6KKj9c
 * https://www.screencast.com/t/euRHwuqbuQu (this is the second part of the screen)

The type of licenses and rest of requirements can be seen at:
 * https://wiki.openmobilealliance.org/display/EP/License+Functionality 

Note: the license needs to be inserted inside of the xml document that contains the object.

**Comment by SvanteAlnas** [comment]
1) If the license statement should be inserted when submitting an registration then the user are not able to change it. For example both OMA and Apache 2.0 license statement expect specific individual information in the statement, not only the template. If implemented as proposed then it is only the template so for example the copy write owner and year in the Apache 2.0 license will not be included. 

2) If the license statement is already included in the file, should the tool replace it and in that case under what conditions? If the statement is formatted as free text (XML Comment) how should the tool identify what should be removed?

3) If implemented as proposed the export will not contain the license statement so the user is never able to verify the content of the file before submission to OMNA.

**Comment by jpradocueva** [comment]
Answering each comment:

1. The idea is that when the user select the license, this license is displayed in the lower part of the tool.
    Here the user can add year and name.
2. The LwM2M Editor tool doesn't produce any license. So it is ok to assume that there is no license at the time of submitting the registration to OMNA. In any the tool will parse for the comments in the tool and these can be listed in the lower portion window. The user has the ability to modify the license as she please. The last content is the one that will be incorporated in the tool as a license.

3. We should include any comment in the file in the license

**Comment by SvanteAlnas** [comment]
The Dev server is now updated with the new functionality:
-	Separate license editor added so the user are able to import/export and edit the license separated from the submission to OMNA
-	License that the user are able to include will be added to existing license, if any exist
-	An folder on the server contains all available licenses as text-files so it is easy to add additional licenses if needed
-	It is not possible to submit an object to OMNA without at least 100 characters license text, this number needs to be defined
-	The license text is stored as an XML comment after the XML declaration in the object. For example existing objects released with the OMA license statement works with this
-	Invalid characters that is not allowed in an XML comment is removed and a warning is displayed, “—“ is replaced with “-“

**Comment by jpradocueva** [comment]
@SvanteAlnas  Problems with the current draft:
1/ We need to add a tick box in the OMNA registration page, indicating that the user has selected the license. As we have the "License Editor" in the menus, it is not clear than first you need to add a license or how it works
2/ In the object we need to add a reminder with a link that a license is needed for OMNA registration
I got a failure at the time of submission a test registration. I believe that in the DEV area the registration submission should work ok, correct?

**Comment by SvanteAlnas** [comment]
1) Isn’t this the same thing as validating that there are at least an license statement with 100 characters? If you want an additional checkbox it should be if the object has an license statement (length > 0), it does not need to be the only one OMA provide.
2) Do you want an additional reminder except that it is not possible to register unless there is an license statement with at minimum 100 characters? I’m not sure if email works in dev area, check with Nathan.

**Comment by jpradocueva** [comment]
1/ Remove the license length check
2/ Add a checkbox with this title:  "Confirm that your Object has a License Statement  X   if not please [add it here](http://devtoolkit.openmobilealliance.org/OEditor/License)
3/ Disable "Register" button until the checkbox is ticked.

**Comment by SvanteAlnas** [comment]
Done in Dev area Ver 1.4.001

Did you also wanted any change in this sentence?
_Thanks, you have successfully submitted your registration to OMNA. OMNA staff will contact you if further information is needed or they will publish it in OMNA._

**Comment by jpradocueva** [comment]
@SvanteAlnas 
If the new functionality of submitting the registration via GitHub is going to take too much time, then we need to have a interim solution.
In the Note at the time of submitting the registration we should indicate: 
``Note: OMA Device Management Working Group has two weeks to review this registration. Please follow up any feedback at: https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues ``

**Comment by jpradocueva** [comment]
- [ ] Change the existing statement in the License Editor in order to assist the user to complete the licenses correctly.
```
Please remember to update the licenses with your company details, see link for assistance: https://wiki.openmobilealliance.org/display/TOOL/LwM2M+License+Editor 
```

**Comment by SvanteAlnas** [comment]
Done in Ver: 1.4.002

**Comment by jmudge** [comment]
- [ ] add clarification to license editor
Current page
![image](https://user-images.githubusercontent.com/11298435/30277747-a0895708-9700-11e7-9025-2cec3c75a0ca.png)

Suggested updates:
![image](https://user-images.githubusercontent.com/11298435/30278705-10daad48-9703-11e7-87b7-586af83ff7aa.png)

**Comment by jmudge** [comment]
@SvanteAlnas 
![image](https://user-images.githubusercontent.com/11298435/30281151-8cf851d6-9709-11e7-98da-d875b3dd750f.png)

**Comment by SvanteAlnas** [comment]
Missing library added so the error is gone, its still not possible to sen mail from the dev-server
