### ISSUE TITLE
Connect OMNA submission with GitHub repo

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#11]
In order to minimize the backend work, investigate how to send the registration from the LwM2M Editor tool to OMA corresponding repository.

**Comment by SvanteAlnas** [comment]
To be able to do that on behalf of the user that means that the user must first login in the tool with OAuth using GitHub account, should that be an requirement that the user first needs to do before an registration to OMNA is possible?

**Comment by jpradocueva** [comment]
We could indicate that if they want to receive feedback via GitHub they need to do the login. If they don't have a GitHub account, then it is not possible for them to follow the feedback. I will expect that the large majority of people will log into GitHub.
Does this help?

**Comment by jpradocueva** [comment]
@SvanteAlnas 
1/ Call for an action:
   "If you want to receive feedback on this registration, please log in with your GitHub account"
    "Your registration is logged [here](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues)
2/ If user doesn't log in with his/her account then we will use a GitHub system account to log in.

**Comment by jpradocueva** [comment]
This is a repository for testing.
https://github.com/OpenMobileAlliance/test-registry/issues

**Comment by jpradocueva** [comment]
- [ ] add a new license to "About"  https://github.com/octokit/octokit.net/blob/master/LICENSE.txt

**Comment by SvanteAlnas** [comment]
Done in ver 1.4.003
Service account needs to be created from the owner of the repository and currently it is JP, not OMA that owns it

**Comment by jpradocueva** [comment]
@SvanteAlnas Done!
test-registry is now connected to OMA organization and you are marked as administrator.

**Comment by SvanteAlnas** [comment]
Configuration file updated so now registrations in the Dev area will go to test-registry

**Comment by jpradocueva** [comment]
@SvanteAlnas I have done a test from the dev_tool.
See my comments in https://github.com/OpenMobileAlliance/test-registry/issues/5 
Also, the tool indicates that it failed to submit the registration but I still got the email confirmation.

**Comment by jpradocueva** [comment]
@SvanteAlnas  The production repository: https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues where the tool will be uploading the OMNA registrations is ready.
