### ISSUE TITLE
Create a new GitHub Account for the tool access

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#12]
Create with Read access as Member and use the Helpdesk email account.
Send details for the account to Svante.

**Comment by jpradocueva** [comment]
@SvanteAlnas 
1/ Identify how to create a service account for OMA, and pass the information to Joaquin.

**Comment by jpradocueva** [comment]
* [ ] Move to OMA Admin all the control and payment.

**Comment by SvanteAlnas** [comment]
Done in Dev area, Ver 1.4.003.
Config file needs to be updated with correct service account when it created.
However, the service account needs to be created from the owner of the repository and currently it is not OMA that owns it

**Comment by jpradocueva** [comment]
@SvanteAlnas 
Done, I have transferred the repo "test-registry" to OMA as organization.

**Comment by SvanteAlnas** [comment]
Configuration file updated so now registrations in the Dev area will go to test-registry
