### ISSUE TITLE
Ask Nathan if we can receive emails from the submitter directly.

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#13]

**Comment by jpradocueva** [comment]
@Joaquin
 chase this with Nathan

**Comment by jpradocueva** [comment]
@SvanteAlnas 
Nathan has indicated that you should be able to indicate in the submission form who was the submitter of the registration.

**Comment by jpradocueva** [comment]
At the of registration an email should be sent by the system to: ( from DSO)
 * Submitter,
 * DSO@MAIL.OPENMOBILEALLIANCE.ORG,
 * Svante,
 * and remove the link to the metadata content from the email and metadata file
Content as today
![image](https://user-images.githubusercontent.com/3258579/29842447-bc0fd986-8cbd-11e7-970f-86c8239b204a.png)

GitHub content:
 * Remove Submitter email and name.

**Comment by SvanteAlnas** [comment]
Done in the Dev area, the configuration file defines the sender mail address wich needs to be updated when the functioanllity is ready for prod.

**Comment by jpradocueva** [comment]
The submitter name is missing from GitHub Issue and from the email to the Helpdesk.

**Comment by SvanteAlnas** [comment]
It is in "Registration name"

Do you want to change it to "Submitter's name"?

**Comment by jpradocueva** [comment]
Yes please, I think that it reflects better the field name.

**Comment by jpradocueva** [comment]
There was no way to do it, Svante create a new email proxy to send the emails from the Dev area
