### ISSUE TITLE
Talk to Legal Counsel about GitHub Licenses for the LwM2M Editor Tool

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#14]

**Comment by jpradocueva** [comment]
1/ For each license file check: what elements need to be filled in by the submitter

**Comment by jpradocueva** [comment]
@SvanteAlnas 
I am in the process of reviewing the following licenses suggested by OMA Legal Counsel for the LwM2M License Editor Tool: 

**Apache 2.0**
  * https://github.com/jpradocueva/apache20/blob/master/LICENSE

**MIT License**
  * https://github.com/jpradocueva/mit/blob/master/LICENSE

**BSD 2- clause** “Simplified” License
  * https://github.com/jpradocueva/bsd2/blob/master/LICENSE

**Creative Commons Attribution 4.0**
  * https://github.com/jpradocueva/cc-by-4-0/blob/master/LICENSE.txt

**Creative Commons 1.0 Universal**
  * https://github.com/jpradocueva/cc-1-0/blob/master/LICENSE.txt

**Comment by jpradocueva** [comment]
@SvanteAlnas 
For what I have been able to check, all the new licenses pass the validation process, despite the placeholders to be filled by the submitter.

Pending Tasks
- [ ] Svante to validate if the licenses proposed here have any validation problem
- [ ] Joaquin to extract for each license what fields the submitter needs to complete and add it to the guidelines and connected with the LwM2M License Editor Tool

**Comment by SvanteAlnas** [comment]
These 5 files does not have any validation problem. However, the content of these files are different compared to the previous you provided. The new one are using a not so nice formatting and in addition some variables/formatting that is harder to read in text format.

Example from the beginning of the BSD 2.0 the new one looks like this:
_

> Copyright (c) <<var;name=copyright;original= <year> <owner>;match=.+>> All rights reserved.

_

The old one starts with this:

> _BSD 2-Clause License
> 
> Copyright (c) 2017
> All rights reserved._

I have keeps the old once on the server with the addition “(old)” as reference. In my view the old one was formatted in a much better way compared to the new links you provided.

Please upload the license files to the App_Data server folder with the file name you want to see presented with the addition “.txt” in the filename. To validate that there are no encoding error use the editor and add the license one by one and you will get an error message directly in case there are any encoding error. 

The file Creative Commons Attribution 4.0 also contains UTF-8 charters (which works fine in the tool and in the XML file), however the owner of the license file may also have it in plain text format which might be preferred by the consumer of the object that will use this license. 

BR
Svante

**Comment by jpradocueva** [comment]
I agree, the licenses that our legal has sent us is not well-formated, difficult to read and with strange notations. I have asked to change to the old ones that we have and for the Creative Common licenses to receive a new set that is correctly formatted and without strange notations ... let's see what we get

**Comment by jpradocueva** [comment]
Latest set of licenses provided by our legal department:

* [CCO-1.0](https://github.com/jpradocueva/cc-1-0)

* [MIT](https://github.com/jpradocueva/mit)

* [Apache 2.0](https://github.com/jpradocueva/apache20)

* [BSD-2.0](https://github.com/jpradocueva/bsd2)

* CC-BY-4.0 still missing, there is a problem with the license.

**Comment by jpradocueva** [comment]
Still pending OMA Members review of the licenses.

**Comment by jpradocueva** [comment]
- [ ] Indicate which License fields need to be completed by the submitter

**Comment by jpradocueva** [comment]
- [ ] Check with OMA Legal Counsel the final list of licenses
- [ ] Check with OMA DM if further licenses are needed.

**Comment by jpradocueva** [comment]
- [ ] Submitter should not be able to modify the content of a selected license (drop menu), the only input may be allowed is: company name and year. 
- [ ] In any case, the tool will allow the submitter to add their own license.

**Comment by jpradocueva** [comment]
Done!
