### ISSUE TITLE
Pre-loaded licenses

### ISSUE THREAD

**Issue by SvanteAlnas** [OpenMobileAlliance/OMA_LWM2M_Editor#15]
The pre-loaded licenses that we have should be updated so they works without an encoding warning. That means that they should be formatted so they are following the formatting rules that is required on XML-Comments

**Comment by jpradocueva** [comment]
@SvanteAlnas  Ok, but what is supposedly that I need to do?

**Comment by SvanteAlnas** [comment]
Yes, the license statement must be compatible with the formatting of an XML comment so "--" are not allowed and that exist in some of the license statements.
