### ISSUE TITLE
New statement to License Editor

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#17]
@SvanteAlnas 
Add a message for certain licenses:  "For the following license you need to provide some extra information, for more information click here" (wiki page)

Joaquin to link to the wiki page

**Comment by SvanteAlnas** [comment]
Done in Dev area Ver 1.4.001
Remaining from JP: List of licenses that need additional info and link to wiki

**Comment by SvanteAlnas** [comment]
Wiki page is handled in issue #14
