### ISSUE TITLE
Reusable Resource Description

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#19]
Possible options to update a reusable resource description:
- [ ] 1a/ Modify the schema by introducing a new element for the variable part of the reusable description
1b/ Modify the extraction of the xml document with a special set of characters that it is not possible to use in the description
- [ ] 2/ Present a read only part if it match OMNA, reminder part is presented in a editable box
- [ ] 3/ Make it editable the whole description (reverse back) & add a note in the best practice guidelines that the original description should be kept.
In any case the technical specs need to be updated to reflect the solution.

**Comment by jpradocueva** [comment]
- [ ] The group agreed to make the reusable resource description fully editable.

**Comment by SvanteAlnas** [comment]
Done in Ver: 1.4.002
