### ISSUE TITLE
Import from a TS

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/OMA_LWM2M_Editor#2]
After importing an object from OMA-TS-DM_StdObj-V1_3-20121009-C and viewing it, I clicked on the "Import" option, selected another TS and clicked on "Upload TS". Three objects could be selected, all with 0 nodes. Selected one, clicked on "Import" button and "View" and an object from OMA-TS-DM_StdObj-V1_3-20121009-C was displayed instead of the new TS.

**Comment by jpradocueva** [comment]
These issues were resolved before launching the tool.
