### ISSUE TITLE
Registration of Reusable Resources doesn't need Software License

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#23]
We need to accommodate new requirements to avoid the use of imposing a software license when registering Reusable Resources. 
These resources don't need a software license at the time of registration.
All the resources will be registered with a default license and the License Editor is not required.

**Comment by SvanteAlnas** [comment]
We don’t have any default License. If the editor automatically should add any “default” license, which condition should trigger that and when in the editor?

**Comment by jpradocueva** [comment]
I believe that for the Registration of Reusable Resources we don't need any license. Can we by pass the need of the editor when registering a Reusable Resource?

A different problem is what should be the license of the Common.xml file. This file contains all the reusable resources.

**Comment by jpradocueva** [comment]
@Jpradocueva
Resolve the Reusable Resource license problem.

**Comment by jpradocueva** [comment]
Each time that a reusable resource is used in the editor mode the corresponding reusable resource license needs to be added to the the License Editor window, e.g.

If I use reusable resource 4000, we need to add to directly to the file without modifying it:
Present the reusable resources licenses as read only in the License Editor.

```
Reusable Resource <4000> License
   Apache 2.0 bla, bla
    kdkdkd
```

**Comment by jpradocueva** [comment]
DM confirm that it is necessary to collect a software license for Reusable Resources.
Also, it is not necessarily to insert the reusable resource license inside of the Object that uses this reusable resource
