### ISSUE TITLE
Add LwM2M Schema to the top level Editor Menu

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#24]
Add a link to the LwM2M Schema next to the Registry API, Guidelines, etc.
It is a pain to find the schema, lets add it clearly to the editor tool

**Comment by jmudge** [comment]
@SvanteAlnas Pending

**Comment by jpradocueva** [comment]
- [ ] Add the schema to the front page of the guidelines
- [ ] Revise guidelines to be aligned with the latest functionality

**Comment by jpradocueva** [comment]
The Guidelines page on the LwM2M editor has been updated to collect all the necessary info:
https://wiki.openmobilealliance.org/display/TOOL/Introduction+to+LightweightM2M
