### ISSUE TITLE
License Drop down menu bug

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/OMA_LWM2M_Editor#25]
When mulitiple licenses are selected to be viewed the information being displayed is incorrect.

Steps
1. Select a license from the drop down menu i.e Apache
2. Select another license to view from the drop down menu i.e BSD-2-Clause
3. The information being display still has the Apache information being displayed but the BSD-2-Clause license information added below.

The only way to view a license correctly is to:
1. 1. Select a license from the drop down menu i.e Apache
2. Click out of the License Editor page i.e  Click 'Import'
3. Select 'License Editor' function
4. Select the License to append and the correct information is displayed.

**Comment by SvanteAlnas** [comment]
This is expected, its decided that the tool will not remove any thing in the file, only append license. If you as a user want to remove then select all license text in the text box and delete it first.

**Comment by jpradocueva** [comment]
The tool is designed to add multiple licenses without removing previous license.
