### ISSUE TITLE
Spelling Mistake in BSD-3-Clause

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/OMA_LWM2M_Editor#26]
Copyright 2016 <compnay name>. All rights reserved.

Compnay should be company

Also shouldn't there be an option to update the Year   i.e  Copyright <yyyy> <company name>

**Comment by SvanteAlnas** [comment]
Yes, you are already able to edit the license, its an editable text field. Additional description what to update etc will be provided in the wiki page.

All license text are provided by OMA’s legal team, these files are stored as provided by them on the server.

**Comment by jmudge** [comment]
I believe that “2016” should be replaced by “<year>” in the BSD-3-Clause. Perhaps this will need to be run by the OMA lawyer.

**Comment by jpradocueva** [comment]
- [ ] Joaquin will update the BDS-3 license to correct these mistakes.

**Comment by jpradocueva** [comment]
The file has been corrected, with: <year> and <copyright holder>.
