### ISSUE TITLE
License LwM2M Editor enhancement

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#29]
@SvanteAlnas DM agreed to add further requirements to the License Editor:

- [ ] Submitter should not be able to modify the content of a selected license (drop menu), the only input may be allowed is: company name and year. 
- [ ] In any case, the tool will allow the submitter to add their own license.

**Comment by SvanteAlnas** [comment]
Done in ver 1.4.003 in the Dev area

- License are changed to one read only part with existing license.  
- Another TextBox is added with the new license. 
- Addition alternative is added in the drop down menu to add own license. 
- If the added license is an preloaded license then it is shown as read only. 
- Preloaded licenses are allowed to use parameters that will be shown and the user need to fill them in before submission is possible. 
- Syntax for adding parameters in the license file is: “@@Label(Description)” without quotes. For example “Copyright (c) @@Year(Year of the copyright) @@Name(Name of the copyright holders)”. 
- Parameters are allowed to be repeated with the same Label, in that case the user will only need to enter the value once.

**Comment by jpradocueva** [comment]
* [ ] Update licenses with the naming schema @@name(description)

**Comment by jpradocueva** [comment]
I have validated the license editor and it works with the new files that contain the corresponding parameters.
