### ISSUE TITLE
Object 3336 Location differs from IPSO's definition

### ISSUE THREAD

**Issue by tritonzhu** [OpenMobileAlliance/OMA_LWM2M_Editor#32]
In the online [DDF](http://www.openmobilealliance.org/tech/profiles/lwm2m/3336.xml), object 3336 uses resource 5514 for Latitude and 5515 for Longitude

While in [IPSO Alliance's definitions](https://github.com/IPSO-Alliance/pub/blob/master/reg/xml/3336.xml), 5513 is for Latitude, 5514 for Longitude and 5515 for Altitude

**Comment by jpradocueva** [comment]
@seanmcilroy29 
Could you please investigate this issue?
Once we understand the problem, we will raise an Issue for DM WG.

**Comment by seanmcilroy29** [comment]
On the 11th Apr IPSO applied an updated the DDF with [resource 5513](https://github.com/IPSO-Alliance/pub/commit/cbb992290b22ee6e8f4b23a272cf3dde888342fb#diff-82cc4e8dcd81faf86c85bbb611bd658c) This update will now be added as an issue for the DM WG to review

**Comment by seanmcilroy29** [comment]
@jpradocueva Issue [#254](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/254) has been added for the DM WG to review the updated object

**Comment by jpradocueva** [comment]
This issue can be tracked in  #254
