### ISSUE TITLE
Label the OMNA Submission "OMNA-Registration" 

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#34]
* [ ] Is possible to marked a new OMNA registration with the label "OMNA-Registration"? This label is already available in the repo: OMA_LwM2M_for_Developers

**Comment by SvanteAlnas** [comment]
Done in Dev, ver 1.4.004

**Comment by SvanteAlnas** [comment]
Done in 1.4.005

**Comment by jpradocueva** [comment]
If the submitter does log with his/her own account then the label is not created. This limitation is imposed by GitHub.
