### ISSUE TITLE
Problem on file name when is exported from the tool.

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#35]
* [ ] for some reason the LwM2M Editor tool is changing the name of the file previously imported.
       It is important to export a file with the same name as when it was imported into the tool. It creates a few problems if we try to integrate this exported file in a GitHub repository, the name is different from the imported name.

**Comment by SvanteAlnas** [comment]
1) The name is not stored in the object so after import it's gone. 
2) The tool ensure that you are able to register multiple objects with the same name since we don’t specify that the name must be unique. The only way to do that is to uniquely assign new names when registered.
