### ISSUE TITLE
Add to the user and helpdesk email the link to the New GitHub Issue 

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#37]
* [ ] The email sent to the submitter and to the helpdesk should also contain the link to the GitHub Issue. or at least the link to the GitHub Issues page.

**Comment by SvanteAlnas** [comment]
Done in the dev area, link is to the created issue

**Comment by jpradocueva** [comment]
Confirmed.
