### ISSUE TITLE
The Download Object link is displaying the Object in the browser

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#38]
* [ ] Something is different, before I believe that the "Download Object" allow us to down load the file but now it is displaying the file in the browser.  We need download the file in order to perform validation on the file itself.

**Comment by SvanteAlnas** [comment]
Then you need to select "save link as.." or similar in the browser. 

When downloading from the tool the file is created in the tool and zipped and browsers usually don't show zip files themselves so they download it. The OMNA files are stored as XML files on the server and the link goes directly to the file repository.

**Comment by jpradocueva** [comment]
ok, thanks for the update. Perhaps I was using a different browser.
I am closing this one.
I believe that we can proceed with moving the tool to production, if all the issues have been clear.

**Comment by jpradocueva** [comment]
@SvanteAlnas the problem doesn't go away by "Saving as" the file. When the file is "Saving as" it incorporates the "tags" provided by the browser and fail validation. 
Please give it a try yourself.

I suggest to use the function "Export" as in the tool rather than view in the browser. In the LwM2M Editor tool the export function downloads the file. In this particular case the link open the file in the browser. Something is different.

**Comment by SvanteAlnas** [comment]
Link changed to download the file as zip-file. Default behaviors for browsers is to download zip file
