### ISSUE TITLE
Create a new schema for the Common.xml file

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#39]
Create a new schema for storing the content in the Common.xml file

**Comment by jpradocueva** [comment]
* [ ] Add the same functionality to support links to the TS documents as in the DDF.xml"
* TS (contains a URL), TSLink=1 if visible

**Comment by SvanteAlnas** [comment]
Done
1) We need to decide the filename and URL of the file
2) The existing Common XML needs to be updated

**Comment by jpradocueva** [comment]
@Svante.
Could you please confirm that the following changes to the schema are correct?

* ```RangeEnumeration```
 - [ ] Added ```minOcurs="0" ```  and ``` type="xs:string" ```

* ```Units```
 - [ ] Added ``` type="xs:string" ```

* Comment the usage of TS and TSLink

See below:

```
                          <xs:element name="RangeEnumeration" type="xs:string" minOccurs="0"/>
                          <xs:element name="Units" type="xs:string" minOccurs="0" />
                          <xs:element name="Submitter" type="xs:string" />
                          <xs:element name="Description" type="xs:string" />
                          <xs:element name="TS" type="xs:string" minOccurs="0" />
                          <!-- TS it is a Link to the technical specification (word, pdf etc.)  -->
                          <xs:element name="TSLink" type="xs:unsignedByte" minOccurs="0" />
                          <!-- TSLink 0 => if link to TS should not be visible, 1 => if link to TS should be visible (default) -->
                        </xs:sequence>
```

**Comment by jpradocueva** [comment]
- [ ] Convert the TS and TSLink into attributes of "name"

**Comment by SvanteAlnas** [comment]
That's possible but why have some of the child elements as elements and other as attribute? I recommend to use the same syntax for all child elements. So either RangeEnumeration, Unit, Sumbitter etc should be attributes or child elements. However i don't recommend to have Description as attribute since it contains CDATA section. That is still possible but more complex than needed.

**Comment by jpradocueva** [comment]
We agreed don't use attributes at this moment. It will require large numbers changes to the current data without clear benefit.
