### ISSUE TITLE
Incorrect configured or missing elements in the LWM2M OMNA database

### ISSUE THREAD

**Issue by SvanteAlnas** [OpenMobileAlliance/OMA_LWM2M_Editor#41]
Object ID 10261 is missing information

Incorrect configuration of Object ID 3352, 3353, 3361 etc. The URN is not valid, i.e. it includes wrong object ID

**Comment by seanmcilroy29** [comment]
Object ID 20261 - This was allocated to Smartlogic but they've declined to use this object so it's been removed.

URN updated - On the request of the submitter the Objects had been moved from x-label to ext-label but the urn had not been updated.

**Comment by jpradocueva** [comment]
@seanmcilroy29 
Please scroll down in this page http://devtoolkit.openmobilealliance.org/OEditor/Default.
You will see that also the some ObjectID numbers in the URN are not correct: 3352, 3353, 3361

**Comment by seanmcilroy29** [comment]
PROD area updated with DEV changeshttp://devtoolkit.openmobilealliance.org/OEditor/Default
Changes now reflected in PROD area
