### ISSUE TITLE
Populate the new Common.xml file using the Common.xsd

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#43]
- [x] Use the new  Common schema to populate the content of the Common.xml
- [x] Change the names of the Common.xsd Schema to something more relevant e.g. ```reusable_resources-v1_0.xsd```
- [x] Add a version to the schema
  * Upload the new schema to the profiles folder
  * http://www.openmobilealliance.org/tech/profiles/reusable_resources_V1_0.xsd

**Comment by seanmcilroy29** [comment]
Updates applied and new schema uploaded to profile folder

**Comment by jpradocueva** [comment]
@seanmcilroy29 we have a new reusable_resources schema. It was produced yesterday. We will review it tomorrow in our call.

**Comment by jpradocueva** [comment]
reusable_resources_v1_0.xsd file needs to be updated with the new media types: Corelnk, Unsigned Integer

**Comment by jpradocueva** [comment]
- [ ] Does common resources need to indicate the compatibility to the LwM2M version?

**Comment by jpradocueva** [comment]
Reusable Resources are protocol independent. If a Reusable Resource is changed then a new number is needed.
