### ISSUE TITLE
Export an object - 

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/OMA_LWM2M_Editor#5]
When the MO urn:oma:mo:oma-dm-devinfo:1.2 is imported and then exported the first line of the exported file is: "
<?xml version="1.0" encoding="UTF-8"?><!--"

This does not quite match REL's MO guideline page http://member.openmobilealliance.org/ftp/rel/P-N-G/SupportFiles_MO.shtm
 that has the first line "<?xml version="1.0" encoding="UTF-8"?>"

Comment
Suggest the suffix "<!--" be moved onto the next line.

**Comment by jpradocueva** [comment]
These issues were resolved before launching the tool.
