### ISSUE TITLE
Invalid Object Version

### ISSUE THREAD

**Issue by SvanteAlnas** [OpenMobileAlliance/OMA_LWM2M_Editor#54]
Some objects in OMNA registry contains Invalid versions of the object

From the TS:
Object Version format
The Object Version of an Object is composed of 2 digits separated by a dot ‘.’

**Comment by seanmcilroy29** [comment]
Currently, all OMA documents are represented with a ‘_’ between the versioning: example OMA-TS-LightweightM2M-V1_0_1-20170704-A.pdf.
If the underscore ‘_’ is replaced by a dot ‘.’ then the page returns a 404 error when the user clicks the link.
Is there a way for the tool to convert the object versioning for the TS from -V1_0- to -V.1.0- or for the tool to accept the underscore ‘_’?
If not do you have any suggestions?

**Comment by seanmcilroy29** [comment]
Currently, all OMA documents are represented with a ```_``` between the versioning: example OMA-TS-LightweightM2M-V1_0_1-20170704-A.pdf.
If the underscore ```_``` is replaced by a dot ```.``` then the page returns a 404 error when the user clicks the link.
Is there a way for the tool to convert the object versioning for the TS from ```-V1_0-``` to ```-V.1.0-``` or for the tool to accept the underscore ```_```?
If not do you have any suggestions?

**Comment by jpradocueva** [comment]
@SvanteAlnas I try to find the error with the OMNA registry and I cannot find it.

**Comment by SvanteAlnas** [comment]
Error, Object ID: 2 has an invalid Version Value!
Error, Object ID: 3 has an invalid Version Value!
Error, Object ID: 4 has an invalid Version Value!
Error, Object ID: 5 has an invalid Version Value!
Error, Object ID: 7 has an invalid Version Value!

From the TS:
Object Version format
The Object Version of an Object is composed of 2 digits separated by a dot ‘.’

All the objects above nos not have the versioning format as specified in the TS

**Comment by jpradocueva** [comment]
I understand the problem but I try to find where do you see this error. Where in the Editor tool can you find this error? I don't see it.
The group has confirmed that the Object Version and the File name version are not the same. This will create lots of problems. I was asked to provide an update on how it could be resolved.

**Comment by SvanteAlnas** [comment]
1) When you open an object with invalid versioning the tool will not show the version in the object
2) If you try so save an object with that version then the tool will give you an error that the version is incorrect and not possible to save
3) If you use the API and ask for latest version of an object of that Object ID you should expect an undefined response from the API

**Comment by jpradocueva** [comment]
@SvanteAlnas do you have the link to check if these errors have been clear?

**Comment by SvanteAlnas** [comment]
I only have it in the Dev area, waiting for you project to finalize it so its only verifying the DDF.XML that is used by the Dev area. All issues has been cleared. You find the verification page at:
http://dev_devtoolkit.openmobilealliance.org/OEditor/OMNAVerify
