### ISSUE TITLE
Error message being generated when registering an Object

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/OMA_LWM2M_Editor#55]
Currently, an error message is being generated when anybody is submitting an object for registration

```Sorry, due to internal error it was not possible to submit the registration for the moment, please try later. Detailed error: 'Failure sending mail.'.```

I've done a number of tests, and everything appears to be working in the tool and the object is being registered in GitHub correctly, however, i believe the error is being created because an email notification to the submitter is failing.

**Comment by SvanteAlnas** [comment]
The error comes from OMA's Server:
    <add key="SMTP" value="omaportalweb.hostedoma.org"/>
    <add key="SMTPPort" value="25"/>

Nathan, could you verify that it works?

**Comment by nathan-omaorg** [comment]
The SMTP service had not started after the last restart. I have set the service to start automatically so this should not happen again. Let me know if it's still an issue and I'll investigate further.
