### ISSUE TITLE
Changes to the current LwM2M schema.

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#58]
- [x] LwM2M v1.1 introduces a new schema lwm2m-v1_1.xsd
   * https://github.com/OpenMobileAlliance/LwM2M-v1_1
- [x]  What is the impact on the tool:
   - [x] When creating a new object select the Version
   - [x] Validate ```LwM2MVersion``` & ```schema reference```
   - [x] Add the new functionality in the editor and viewer in case of new Protocol Version

**Comment by SvanteAlnas** [comment]
Done in 1.5.003

**Comment by jpradocueva** [comment]
The schema can be found: http://www.openmobilealliance.org/tech/profiles/lwm2m.xsd
Expected URL for LwM2M v1.1:
http://www.openmobilealliance.org/tech/profiles/lwm2m-v1_1.xsd

**Comment by SvanteAlnas** [comment]
Done in 1.5.004
