### ISSUE TITLE
Edit an object

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/OMA_LWM2M_Editor#6]
The Tree Operation "Right" button generates stack dumps when there is no right hand object e.g.
Server Error in '/DMEditor' Application.

Object reference not set to an instance of an object.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 

Line 539:            throw new InvalidOperationException("Error!");
Line 540:        XmlNode N1 = CurrentNode.m_Node.NextSibling;
Line 541:        while ((N1.Name != "Node") || (N1.SelectSingleNode("DFProperties/DFFormat/node") == null))
Line 542:            N1 = N1.NextSibling;
Line 543:        N1.AppendChild(CurrentNode.m_Node);

Source File: d:\!Websites\devtoolkit.openmobilealliance.org\Apps\DMEditor\DDFEdit.aspx.cs    Line: 541 
Stack Trace: 
[NullReferenceException: Object reference not set to an instance of an object.]
   DDFEdit.MoveRightButton_Click(Object sender, EventArgs e) in d:\!Websites\devtoolkit.openmobilealliance.org\Apps\DMEditor\DDFEdit.aspx.cs:541
   System.Web.UI.WebControls.Button.OnClick(EventArgs e) +9669962
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +108
   System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) +12
   System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) +15
   System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData) +35
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3562

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.114.0

Comment
Suggest a more user friendly error message is displayed.

**Comment by jpradocueva** [comment]
These issues were resolved before launching the tool.
