### ISSUE TITLE
Update to the verification tool

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#61]
The first object version for Object ID 10260 has been registered.
The validation tool, indicate an error with the duplication of the Object ID. This is not an error, the tool needs to cope with Objects having the same Object ID as long as the URN is unique.

![image](https://user-images.githubusercontent.com/3258579/40131467-ec56cd18-58ee-11e8-8b25-0c86e8f6babd.png)

**Comment by SvanteAlnas** [comment]
The problem is that an error is generated if multiple versions of the same object is registered and that needs to be fixed. 

However, what elements needs to be the same for the same object with multiple versions?
- Name?
- Description?
- Owner? - May not be needed if the owner changed name

**Comment by jpradocueva** [comment]
- [ ]  define what is the criteria to accept a new version of the same object

**Comment by jpradocueva** [comment]
The current criteria is: same ObjectID MUST have different version.

**Comment by jpradocueva** [comment]
The schema can be found: http://www.openmobilealliance.org/tech/profiles/lwm2m.xsd
Expected URL:
http://www.openmobilealliance.org/tech/profiles/lwm2m-v1_1.xsd
