### ISSUE TITLE
OMNA Registry Verification

### ISSUE THREAD

**Issue by SvanteAlnas** [OpenMobileAlliance/OMA_LWM2M_Editor#65]
Add an extra page to validate that the OMNA Configuration is correct. Requirements:
https://wiki.openmobilealliance.org/display/EP/Validation+Criteria+for+OMNA+LwM2M+Registry

It should be possible to validate any URL as OMNA Registry, default value is what's configured en the editor

**Comment by SvanteAlnas** [comment]
Done in 1.5.003 and published in Dev area

Should error check 291 & 311 to avoid Vorto and TS that is published in HTML format?

**Comment by SvanteAlnas** [comment]
Done in 1.5.004

291 and 311 is removed from validation

**Comment by SvanteAlnas** [comment]
Validation of XML Schema reference for objects fails in many cases due to that some objects are using:
http://openmobilealliance.org/tech/profiles/LWM2M.xsd

But the expected URL is:
http://www.openmobilealliance.org/tech/profiles/LWM2M.xsd

Should the tool accept both which means that the incorrect (but working) URL may be included in new registrations?

Both URL's are working but it is only the last that is expected.

**Comment by seanmcilroy29** [comment]
Currently, all the object list http://openmobilealliance.org/tech/profiles/LWM2M.xsd as the XML Schema reference, so if we only accepted http://www.openmobilealliance.org/tech/profiles/LWM2M.xsd then each object file will need to be updated.

**Comment by jpradocueva** [comment]
@SvanteAlnas  let's accept both versions: 
* http://www.openmobilealliance.org/tech/profiles/LWM2M.xsd and 
* http://openmobilealliance.org/tech/profiles/LWM2M.xsd
This will eliminate 168 errors one for each Object registered with OMNA.

**Comment by SvanteAlnas** [comment]
Done in Ver: 1.5.005 and its update din the Dev area

in addition i also accepted the xml schema reference regardless of upper/lower case.
The formal name is "LWM2M.xsd" but several existing object uses "lwm2m.xsd"

Let me know if i should keep that

As long as your web server accept xml schema request regardless of upper/lower case it will work

**Comment by jpradocueva** [comment]
Use lower or uppercase can be a problem in some web servers e.g. (Linux)
