### ISSUE TITLE
License for the Newton JSON Library

### ISSUE THREAD

**Issue by SvanteAlnas** [OpenMobileAlliance/OMA_LWM2M_Editor#66]
To verify the API I have added an very common used JSON library for parsing JSON documents. It is using the MIL License. I have updated the info in About:
http://dev_devtoolkit.openmobilealliance.org/OEditor/About

And there you will find the MIT license used for that library:
http://dev_devtoolkit.openmobilealliance.org/OEditor/LICENSE_Newton.txt

Please verify that OMA accept the MIT license this library is using

**Comment by jpradocueva** [comment]
Yes, it is ok.
