### ISSUE TITLE
Impacts of new LwM2M v1.1 in the tools

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#67]
- [ ]  What is the impact on the tool:
   - [ ] When creating a new object select the Version

   - [ ] Add the new functionality in the editor and viewer in case of new Protocol Version

        Changes in Object Definition (XML Schema)
       Additional Data Types:
            "Unsigned Integer"
            "Corelnk"

**Comment by SvanteAlnas** [comment]
Done in 1.5.004
