### ISSUE TITLE
Change to the registration tool

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#68]
Remove the application with the content of the Object: "Name of the Object"
Change the "Name of the Object" to READ only.

"Description" is READ only at the time of Registration. And if it is empty, then registration is not allowed.

**Comment by SvanteAlnas** [comment]
Done in 1.5.004

Question: Description in some LWM2M objects are very big, is it expected that it must be the same as "short description in OMNA"?

**Comment by jpradocueva** [comment]
The description will be reverse to write.
