### ISSUE TITLE
IPSO Model Anomalies

### ISSUE THREAD

**Issue by SteveOss** [OpenMobileAlliance/OMA_LWM2M_Editor#7]
We have been exporting the XML from the Editor tool and using it to generate code. While doing
this we have discovered a number of anomalies in the use of object properties. We have found three
cases of the use of the same property id for different types and one case where the same property id
has been given different names:

[ipso-anomolies.txt](https://github.com/OpenMobileAlliance/OMA_LWM2M_Editor/files/378366/ipso-anomolies.txt)

**Comment by github-oma** [comment]
Hi Steve,
Could you please confirm that this problem has been resolved?
Sorry for the delay.
Joaquin
