### ISSUE TITLE
Incorrect Object name in the DDF.xml file for Object 10260

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#70]
According to the 10260.xml the Name of the Object is "RDB", but in the DDF.xml it is called "Runtime Database". The name in the DDF.xml file must reflect the value inside of 1026.xml.

**Comment by seanmcilroy29** [comment]
10260 is being displayed as RDB in the DEV area. 
This object has 2 version 1.0 ``Runtime Database`` & 2.0  ``RDB``
![image](https://user-images.githubusercontent.com/8318213/40903514-74c469c8-67cf-11e8-8cfc-675311552b92.png)

**Comment by jpradocueva** [comment]
DevMaster has been updated by Sean to reflect "RDB" in the version 2.0 of 10260.xml Object.
