### ISSUE TITLE
Problems with Common.xml in the DEV area

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#71]
The XML Validation tool points to the DEV area.

This DEV area has problems in, at least Object 3349, all the resources in this Object has a blank-space in the "RangeEnumeration" element.
We need to find out the reason of these discrepancy.

This Issue was raised by mistake in "Test-LwM2M-v1.1" repository: https://github.com/OpenMobileAlliance/Test_LwM2M_v1_1/issues/359

**Comment by seanmcilroy29** [comment]
The problem isn't with the DEV it's with Object 3349.
Each of the resources in this Objects have spaces in each of the RangeEnumerations and this has been reflected in the registry.
The Object needs to be updated to resolve not only with the RangeEnumeration but the Units as well.
![image](https://user-images.githubusercontent.com/8318213/40904422-9b98bd76-67d2-11e8-8393-1e4967ffe664.png)

**Comment by jpradocueva** [comment]
This change in the Commont.xml needs to be reverse as the Reusable Objects were not registered with the blank space.

**Comment by jpradocueva** [comment]
Done by Sean.
