### ISSUE TITLE
Object 17 & 18 have an empty "LwM2M" element

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#74]
Objects 17 & 18 have an empty value in "LWM2M" element. This is not possible to have an empty value when the "DDF" element contains a link to an xml file.

Staff to investigate. 
I believe that removing the links from the "DDF" will resolve this problem.

**Comment by seanmcilroy29** [comment]
Removing the link resolved the issue
