### ISSUE TITLE
Limit the Description field to certain characters 

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#75]
In the OMNA Registration tool. Limit the number of characters in the "Description" field to 134 (3 lines in the OMNA registry)

**Comment by jpradocueva** [comment]
Reverse back the "Description" as READ only according to Issue #68

**Comment by SvanteAlnas** [comment]
Done in 1.5.005

**Comment by jpradocueva** [comment]
@SvanteAlnas I don't see the content of the "Description" in the metadata link. The description content appears empty in the email sent by the system.

**Comment by SvanteAlnas** [comment]
Corrected in 1.5.006 and that is updated in Prod

It was an mistake introduced when we changed the field to read-only and then back again
