### ISSUE TITLE
Publish ver 1.5.005 in Production

### ISSUE THREAD

**Issue by SvanteAlnas** [OpenMobileAlliance/OMA_LWM2M_Editor#78]
- Update About 
- Update Revision History

**Comment by SvanteAlnas** [comment]
Done

**Comment by jpradocueva** [comment]
It seems that production deployment version 1.5006 is ahead of the development (v1.5005). Is this right?
Production
![image](https://user-images.githubusercontent.com/3258579/41881877-aeb64774-789a-11e8-96fd-23295cb14f22.png)

Development
![image](https://user-images.githubusercontent.com/3258579/41881937-047e48fa-789b-11e8-88ed-136ee063d46e.png)
